name: helperfunc Continuous Deployment

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  deploy_to_npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: "https://registry.npmjs.org"

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Build the source code
        run: yarn build

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
