name: helperfunc CD

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install all dependencies
        run: yarn install --frozen-lockfile

      - name: Build source code
        run: yarn build

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
