name: helperfunc CD

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  publish_to_npm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node_version: 14.x
          registry-url: https://registry.npmjs.org

      - name: Install all dependencies
        run: yarn install --frozen-lockfile

      - name: Build source code
        run: yarn build

      - name: Publish to NPM
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}

  publish_to_gpr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          scope: "@0xBooper"
          always-auth: true

      - name: Setup yarn to publish to GPR
        run: yarn config set npmPublishRegistry "https://npm.pkg.github.com"
        run: yarn config set npmAuthToken "${{ secrets.GITHUB_TOKEN }}"

      - name: Install everything
        run: yarn install --frozen-lockfile

      - name: Build the code
        run: yarn build

      - name: Publish to Github Package Registry (GPR)
        run: yarn publish
